export const INCREAMENT = 'INCREAMENT'
export const DECREAMENT = 'DECREAMENT'
export const LOGIN = 'LOGIN'
export const GENERATEROUTES = 'GENERATEROUTES'
export const ADMIN = 'ADMIN'
export const SUPERADMIN = 'SUPERADMIN'
